server: 'irc.twitch.tv'
port: 6667
channel: '#riotgames'
user: 'funknapkin'
password: 'oauth:mj58l4yo1e4y8d4ecggtqihxdqa1nj'
buffer_size: 4096

debug:
    log-level: 'debug' #debug, info, warning, error, critical
    log-file: 'chat.log'
